name: uses-action

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Brokkr
