name: action-outputs

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Brokkr
      - name: Use output
        run: echo "at=${{ steps.greet.outputs.time }}"
