name: github-env

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "BUILT_BY=brokkr" >> "$GITHUB_ENV"
      - name: Read env
        run: echo "built_by=$BUILT_BY"
