name: job-outputs

on: push

jobs:
  producer:
    runs-on: ubuntu-latest
    outputs:
      color: ${{ steps.gen.outputs.color }}
    steps:
      - name: Generate
        id: gen
        run: echo "color=green" >> "$GITHUB_OUTPUT"

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: Consume
        run: echo "got ${{ needs.producer.outputs.color }}"
