name: job-if-failure

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Boom
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "should-not-run"

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Cleanup
        run: echo "cleanup-after-job-failure"
