name: needs-result

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "setup"
  report:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Report
        run: echo "setup-result=${{ needs.setup.result }}"
