name: env-expression

on: push

env:
  BRANCH: ${{ github.ref_name }}
  TAG: build-${{ github.run_number }}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "branch=$BRANCH tag=$TAG"
