name: docker-action

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker action
        uses: ./.github/actions/dockeraction
        with:
          who: Brokkr
