name: if-functions

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Contains
        if: contains(github.event_name, 'push')
        run: echo "contains-ok"
      - name: StartsWith
        if: startsWith(github.ref, 'refs/heads/')
        run: echo "startswith-ok"
      - name: Negative
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "should-not-run"
